"""Recommendations page for CI Bottleneck Analyzer.

Allows the user to select a build and view generated recommendations. Data is fetched from the FastAPI backend.
"""

import streamlit as st
import requests
from typing import List, Dict, Any

BASE_URL = "http://localhost:8000"

def fetch_builds(limit: int = 200) -> List[Dict[str, Any]]:
    try:
        resp = requests.get(f"{BASE_URL}/builds?skip=0&limit={limit}")
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        st.error(f"Failed to fetch builds: {e}")
        return []

def fetch_recommendations(build_id: str) -> List[Dict[str, Any]]:
    try:
        resp = requests.get(f"{BASE_URL}/recommendations/{build_id}")
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        st.error(f"Failed to fetch recommendations: {e}")
        return []

def run():
    st.title("💡 Recommendations")
    st.markdown("---")

    builds = fetch_builds()
    if not builds:
        st.info("No builds available to show recommendations.")
        return

    # Build selection dropdown
    build_options = {f"{b['build_id']} ({b['service_name']}/{b['pipeline_name']})": b['build_id'] for b in builds}
    selected_label = st.selectbox("Select a build", list(build_options.keys()))
    selected_build_id = build_options[selected_label]

    st.subheader(f"Recommendations for {selected_build_id}")
    recs = fetch_recommendations(selected_build_id)
    if not recs:
        st.info("No recommendations found for this build.")
        return

    for rec in recs:
        st.markdown(f"- **{rec.get('title', 'Untitled')}**: {rec.get('description', '')}")
    st.markdown("---")
    st.caption("Recommendations are generated by the bottleneck analysis engine and stored in the database.")
